# Generated by Django 4.1.7 on 2023-11-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='image',
            field=models.FileField(blank=True, upload_to='pages_images/'),
        ),
    ]
